### ISSUE TITLE
Panic `Given values do not represent a cardinality constraint` when constructing a cardinality constraint

### ISSUE THREAD

**Issue by mgudemann** [booleworks/logicng-rs#1]
Given a too large number for a `GE` / `LE` / `EQ` cardinality constraint results in a panic.

I created a test which should be ok but causes a panic
```rust
    #[test]
    fn test_unsigned_bug() {
        let ff = FormulaFactory::new();
        let formula = ff.cc(CType::GE, 9223372036854775808, vec![]);

        assert!(formula.is_falsum());
    }
```
`9223372036854775807` (or `2^63 - 1`) does work. So it is probably some kind of overflow problem. I found this via a bug in my own program.

**Comment by czengler** [comment]
Thanks for your report, we will look into this issue.

**Comment by matthias-jugan** [comment]
Commit 8b5bb9f fixes this issue.

It restricts the `rhs` argument to `u32`, which avoids the internal conversion issues caused by the size of the input. Unfortunately, this means that the provided test is no longer valid code. But the Java version also only allows 32 bit. So I think this is a justifiable restriction.
